const Razorpay = require("razorpay");
const crypto = require("crypto");
const Internship = require("../models/Internship");
const InternshipRegistration = require("../models/InternshipRegistration");
const PlatformSettings = require("../models/PlatformSettings");
const { isValidEmail, isValidObjectId, normalizeEmail, normalizeName, normalizePhone, normalizeText, escapeRegex } = require("../utils/validation");

const razorpay = new Razorpay({ key_id: process.env.RAZORPAY_KEY_ID, key_secret: process.env.RAZORPAY_KEY_SECRET });
const text = (v, max) => normalizeText(v, { maxLength: max });
const ready = () => Boolean(process.env.RAZORPAY_KEY_ID && process.env.RAZORPAY_KEY_SECRET);
const regId = () => `INTREG-${new Date().getFullYear()}-${crypto.randomBytes(4).toString("hex").toUpperCase()}`;
const token = () => crypto.randomBytes(32).toString("base64url");
const hash = (v) => crypto.createHash("sha256").update(String(v)).digest("hex");
const url = (v) => { const value = text(v, 300); if (!value) return ""; try { const u = new URL(value); return ["http:", "https:"].includes(u.protocol) ? u.toString() : ""; } catch { return ""; } };
async function getSettings() { return PlatformSettings.findOneAndUpdate({ key: "platform" }, { $setOnInsert: { key: "platform", registrationFee: 1799, currency: "INR", registrationEnabled: true } }, { new: true, upsert: true, setDefaultsOnInsert: true }); }
function view(r) { return { _id: r._id, registrationId: r.registrationId, fullName: r.fullName, primaryDomain: r.primaryDomain, preferredDuration: r.preferredDuration, registrationFee: r.registrationFee, currency: r.currency, paymentStatus: r.paymentStatus, registrationStatus: r.registrationStatus, razorpayOrderId: r.razorpayOrderId || "", paymentVerifiedAt: r.paymentVerifiedAt || null, createdAt: r.createdAt }; }
function owns(req, r) { const userId = req.user?.id || req.user?._id; if (userId && r.userId && String(userId) === String(r.userId)) return true; const access = String(req.get("x-registration-access-token") || req.body?.accessToken || req.query?.accessToken || ""); return Boolean(!r.userId && access && r.accessTokenHash && hash(access) === r.accessTokenHash); }
function pending(r) { return r.registrationStatus === "payment_pending" && r.paymentStatus !== "paid"; }

exports.getRegistrationOptions = async (_req, res) => { try { const [internships, config] = await Promise.all([Internship.find({ isActive: true }).select("title category branch durations duration durationDays").sort({ createdAt: -1 }).lean(), getSettings()]); return res.json({ success: true, registrationEnabled: config.registrationEnabled, fee: config.registrationFee, currency: config.currency, internships: internships.map((i) => ({ _id: i._id, title: i.title, category: i.category || "", branch: i.branch || "", durations: Array.isArray(i.durations) && i.durations.length ? i.durations.map((d) => ({ label: d.label, durationDays: d.durationDays })) : [{ label: i.duration || `${i.durationDays || 30} Days`, durationDays: i.durationDays || 30 }] })) }); } catch (e) { console.error("REGISTRATION OPTIONS ERROR:", e.message); return res.status(500).json({ success: false, message: "Unable to load internship options right now." }); } };

exports.createRegistration = async (req, res) => { try {
  const b = req.body || {}, config = await getSettings(); if (!config.registrationEnabled) return res.status(403).json({ success: false, message: "Internship registration is temporarily unavailable. Please check back later." });
  const fullName = normalizeName(b.fullName), email = normalizeEmail(b.email), phone = normalizePhone(b.phone); const required = [fullName, email, phone, text(b.city, 80), text(b.state, 80), text(b.country, 80), text(b.educationLevel, 60), text(b.course, 80), text(b.branch, 100), text(b.collegeName, 160), text(b.academicYear, 40), b.primaryInternshipId, text(b.preferredDuration, 80)];
  if (fullName.length < 2 || !isValidEmail(email) || !/^\+?\d{10,15}$/.test(phone) || required.some((v) => !v)) return res.status(400).json({ success: false, message: "Please complete all required fields with valid details." });
  const graduationYear = Number(b.graduationYear); if (!Number.isInteger(graduationYear) || graduationYear < 2020 || graduationYear > 2100 || !isValidObjectId(b.primaryInternshipId)) return res.status(400).json({ success: false, message: "Please provide valid academic and internship details." });
  const rawUrls = [b.github, b.linkedin, b.portfolio], urls = rawUrls.map(url); if (rawUrls.some((v, i) => text(v, 300) && !urls[i])) return res.status(400).json({ success: false, message: "Profile links must use a valid http or https URL." });
  const internship = await Internship.findOne({ _id: b.primaryInternshipId, isActive: true }).select("title durations duration durationDays").lean(); if (!internship) return res.status(400).json({ success: false, message: "Please select an active InternovaTech internship." });
  const durations = Array.isArray(internship.durations) && internship.durations.length ? internship.durations : [{ label: internship.duration || `${internship.durationDays || 30} Days` }], preferredDuration = text(b.preferredDuration, 80); if (!durations.some((d) => d.label === preferredDuration)) return res.status(400).json({ success: false, message: "Please select a duration offered for this internship." });
  const accessToken = token(), userId = req.user?.id || req.user?._id || null, skills = Array.isArray(b.skills) ? [...new Set(b.skills.map((s) => text(s, 40)).filter(Boolean))].slice(0, 15) : [];
  const registration = await InternshipRegistration.create({ registrationId: regId(), userId, accessTokenHash: userId ? "" : hash(accessToken), fullName, email, phone, city: text(b.city, 80), state: text(b.state, 80), country: text(b.country, 80), educationLevel: text(b.educationLevel, 60), course: text(b.course, 80), branch: text(b.branch, 100), collegeName: text(b.collegeName, 160), academicYear: text(b.academicYear, 40), graduationYear, skills, skillLevel: ["Beginner", "Intermediate", "Advanced"].includes(b.skillLevel) ? b.skillLevel : "", github: urls[0], linkedin: urls[1], portfolio: urls[2], primaryInternshipId: internship._id, primaryDomain: internship.title, secondaryInterest: text(b.secondaryInterest, 160), preferredDuration, startPreference: text(b.startPreference, 40) || "Flexible", careerGoal: text(b.careerGoal, 80), referralSource: text(b.referralSource, 80), registrationFee: config.registrationFee, currency: config.currency, paymentStatus: "pending", registrationStatus: "payment_pending" });
  return res.status(201).json({ success: true, registration: view(registration), ...(userId ? {} : { accessToken }) });
} catch (e) { console.error("CREATE INTERNSHIP REGISTRATION ERROR:", e.message); return res.status(500).json({ success: false, message: "We could not save your registration. Please try again." }); } };

exports.createRegistrationOrder = async (req, res) => { try {
  if (!ready()) return res.status(503).json({ success: false, message: "Payment service is temporarily unavailable." }); if (!isValidObjectId(req.params.id)) return res.status(400).json({ success: false, message: "Invalid registration ID." });
  const [r, config] = await Promise.all([InternshipRegistration.findById(req.params.id).select("+accessTokenHash"), getSettings()]); if (!r || !owns(req, r)) return res.status(404).json({ success: false, message: "Registration not found." }); if (!config.registrationEnabled || !pending(r)) return res.status(400).json({ success: false, message: r.paymentStatus === "paid" ? "Registration is already paid." : "Registration payment is currently unavailable." });
  if (r.razorpayOrderId) return res.json({ success: true, key: process.env.RAZORPAY_KEY_ID, order: { id: r.razorpayOrderId, amount: Math.round(r.registrationFee * 100), currency: r.currency }, registration: view(r) });
  const order = await razorpay.orders.create({ amount: Math.round(r.registrationFee * 100), currency: r.currency, receipt: `reg_${r.registrationId}`, notes: { registrationId: r.registrationId, purpose: "internship_registration", ...(r.userId ? { userId: String(r.userId) } : {}) } }); r.razorpayOrderId = order.id; r.paymentStatus = "created"; await r.save(); return res.json({ success: true, key: process.env.RAZORPAY_KEY_ID, order, registration: view(r) });
} catch (e) { console.error("CREATE REGISTRATION ORDER ERROR:", e.message); return res.status(500).json({ success: false, message: "Unable to create your payment order. Please try again." }); } };

exports.verifyRegistrationPayment = async (req, res) => { try {
  const { razorpay_order_id: orderId, razorpay_payment_id: paymentId, razorpay_signature: signature } = req.body || {}; if (![orderId, paymentId, signature].every((v) => typeof v === "string" && v.trim())) return res.status(400).json({ success: false, message: "Missing payment verification fields." }); if (!ready()) return res.status(503).json({ success: false, message: "Payment service is temporarily unavailable." });
  const r = await InternshipRegistration.findById(req.params.id).select("+accessTokenHash +razorpaySignature"); if (!r || !owns(req, r)) return res.status(404).json({ success: false, message: "Registration not found." }); if (r.paymentStatus === "paid") return res.json({ success: true, message: "Payment already verified.", registration: view(r), redirectTo: `/registrationSuccess?registration=${r._id}` }); if (!r.razorpayOrderId || r.razorpayOrderId !== orderId) return res.status(400).json({ success: false, message: "Payment order does not match this registration." });
  const expected = crypto.createHmac("sha256", process.env.RAZORPAY_KEY_SECRET).update(`${orderId}|${paymentId}`).digest("hex"); if (!/^[a-f0-9]{64}$/i.test(signature) || !crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(signature))) return res.status(400).json({ success: false, message: "Invalid payment signature." }); const order = await razorpay.orders.fetch(orderId); if (Number(order.amount) !== Math.round(r.registrationFee * 100) || order.currency !== r.currency) return res.status(400).json({ success: false, message: "Payment amount verification failed." }); const duplicate = await InternshipRegistration.findOne({ razorpayPaymentId: paymentId, _id: { $ne: r._id } }).select("_id").lean(); if (duplicate) return res.status(409).json({ success: false, message: "This payment is already linked to another registration." });
  r.razorpayPaymentId = paymentId; r.razorpaySignature = signature; r.paymentStatus = "paid"; r.registrationStatus = "confirmed"; r.paymentVerifiedAt = new Date(); await r.save(); return res.json({ success: true, message: "Payment verified successfully.", registration: view(r), redirectTo: `/registrationSuccess?registration=${r._id}` });
} catch (e) { console.error("VERIFY REGISTRATION PAYMENT ERROR:", e.message); return res.status(500).json({ success: false, message: "Payment verification could not be completed. Please contact support." }); } };

exports.markRegistrationPaymentFailed = async (req, res) => { try { const r = await InternshipRegistration.findById(req.params.id).select("+accessTokenHash"); if (!r || !owns(req, r)) return res.status(404).json({ success: false, message: "Registration not found." }); if (r.paymentStatus !== "paid") { r.paymentStatus = "failed"; await r.save(); } return res.json({ success: true, registration: view(r) }); } catch { return res.status(500).json({ success: false, message: "Unable to update payment status." }); } };
exports.getMyRegistrations = async (req, res) => { const items = await InternshipRegistration.find({ userId: req.user.id || req.user._id }).sort({ createdAt: -1 }).lean(); return res.json({ success: true, items: items.map(view) }); };
exports.getRegistration = async (req, res) => { if (!isValidObjectId(req.params.id)) return res.status(400).json({ success: false, message: "Invalid registration ID." }); const r = await InternshipRegistration.findById(req.params.id).select("+accessTokenHash"); if (!r || !owns(req, r)) return res.status(404).json({ success: false, message: "Registration not found." }); return res.json({ success: true, registration: view(r) }); };
exports.getAdminRegistrationSettings = async (_req, res) => { const s = await (await getSettings()).populate("updatedBy", "name email"); return res.json({ success: true, settings: { registrationFee: s.registrationFee, currency: s.currency, registrationEnabled: s.registrationEnabled, updatedAt: s.updatedAt, updatedBy: s.updatedBy || null } }); };
exports.updateAdminRegistrationSettings = async (req, res) => { const { registrationFee, registrationEnabled } = req.body || {}, update = { updatedBy: req.user.id || req.user._id }; if (registrationFee !== undefined) { const fee = Number(registrationFee); if (!Number.isInteger(fee) || fee < 1 || fee > 100000) return res.status(400).json({ success: false, message: "Registration fee must be a whole number from ₹1 to ₹100,000." }); update.registrationFee = fee; } if (registrationEnabled !== undefined) { if (typeof registrationEnabled !== "boolean") return res.status(400).json({ success: false, message: "Registration enabled must be true or false." }); update.registrationEnabled = registrationEnabled; } const s = await PlatformSettings.findOneAndUpdate({ key: "platform" }, { $set: update, $setOnInsert: { key: "platform", currency: "INR" } }, { upsert: true, new: true, setDefaultsOnInsert: true }).populate("updatedBy", "name email"); return res.json({ success: true, message: "Registration settings updated successfully.", settings: { registrationFee: s.registrationFee, currency: s.currency, registrationEnabled: s.registrationEnabled, updatedAt: s.updatedAt, updatedBy: s.updatedBy } }); };
exports.getAdminRegistrations = async (req, res) => { try { const page = Math.max(1, Number(req.query.page) || 1), limit = Math.min(100, Math.max(1, Number(req.query.limit) || 10)), query = {}, search = text(req.query.search, 80); if (search) { const re = new RegExp(escapeRegex(search), "i"); query.$or = ["registrationId","fullName","email","phone","collegeName","course","branch","primaryDomain"].map((key) => ({ [key]: re })); } ["paymentStatus","registrationStatus","course","branch","primaryDomain"].forEach((key) => { if (req.query[key] && req.query[key] !== "All") query[key] = text(req.query[key], 160); }); if (req.query.from || req.query.to) query.createdAt = { ...(req.query.from ? { $gte: new Date(`${req.query.from}T00:00:00.000Z`) } : {}), ...(req.query.to ? { $lte: new Date(`${req.query.to}T23:59:59.999Z`) } : {}) }; const [items,total] = await Promise.all([InternshipRegistration.find(query).sort({ createdAt: -1 }).skip((page-1)*limit).limit(limit).lean(), InternshipRegistration.countDocuments(query)]); return res.json({ success: true, page, limit, total, totalPages: Math.max(1, Math.ceil(total/limit)), items }); } catch { return res.status(500).json({ success: false, message: "Failed to fetch registrations." }); } };
exports.getAdminRegistration = async (req, res) => { if (!isValidObjectId(req.params.id)) return res.status(400).json({ success: false, message: "Invalid registration ID." }); const r = await InternshipRegistration.findById(req.params.id).populate("userId", "name email").lean(); return r ? res.json({ success: true, registration: r }) : res.status(404).json({ success: false, message: "Registration not found." }); };
exports.updateAdminRegistrationStatus = async (req, res) => { const status = String(req.body?.registrationStatus || ""); if (!["confirmed", "cancelled"].includes(status)) return res.status(400).json({ success: false, message: "Invalid registration status." }); const r = await InternshipRegistration.findById(req.params.id); if (!r) return res.status(404).json({ success: false, message: "Registration not found." }); if (status === "confirmed" && r.paymentStatus !== "paid") return res.status(400).json({ success: false, message: "Only a verified payment can confirm a registration." }); r.registrationStatus = status; await r.save(); return res.json({ success: true, message: "Registration status updated successfully.", registration: view(r) }); };
