const crypto = require("crypto");
const OfferLetter = require("../models/OfferLetter");
const Purchase = require("../models/Purchase");
const User = require("../models/User");
const { isValidObjectId } = require("../utils/validation");
const generateOfferLetterPdf = require("../utils/generateOfferLetterPdf");

const id = () => `INV-OL-${new Date().getFullYear()}-${crypto.randomBytes(3).toString("hex").toUpperCase()}`;
const fmt = (letter) => ({ offerLetterId: letter.offerLetterId, status: letter.status, issueDate: letter.issueDate, internshipTitle: letter.internshipTitle, domain: letter.domain, duration: letter.duration, verificationUrl: `/verify-offer-letter/${letter.offerLetterId}` });
async function getOwnedLetter(purchaseId, userId) { return OfferLetter.findOne({ purchaseId, userId }); }

exports.downloadMyOfferLetter = async (req,res) => { try { if(!isValidObjectId(req.params.purchaseId)) return res.status(400).json({success:false,message:"Invalid purchase ID."}); const letter=await getOwnedLetter(req.params.purchaseId,req.user.id||req.user._id); if(!letter) return res.status(404).json({success:false,message:"An official offer letter has not been issued for this internship."}); if(letter.status==="revoked") return res.status(410).json({success:false,message:"This offer letter has been revoked."}); const safe=letter.candidateName.replace(/[^a-z0-9]/gi,"_").replace(/_+/g,"_");res.setHeader("Content-Type","application/pdf");res.setHeader("Content-Disposition",`attachment; filename="InternovaTech_Internship_Offer_Letter_${safe}_${letter.offerLetterId}.pdf"`); await generateOfferLetterPdf({res,offerLetter:letter}); } catch(e){console.error("DOWNLOAD OFFER LETTER ERROR:",e.message); if(!res.headersSent) res.status(500).json({success:false,message:"Failed to generate offer letter."});} };
exports.verifyOfferLetter = async (req,res) => { const letter=await OfferLetter.findOne({offerLetterId:String(req.params.offerLetterId||"").trim().toUpperCase()}).lean(); if(!letter) return res.status(404).json({success:false,message:"Offer letter not found."}); return res.json({success:true,valid:letter.status==="issued",status:letter.status,offerLetter:{referenceId:letter.offerLetterId,candidateName:letter.candidateName,internshipDomain:letter.domain,issueDate:letter.issueDate}}); };
exports.getMyOfferLetters = async (req,res) => { const items=await OfferLetter.find({userId:req.user.id||req.user._id}).sort({createdAt:-1}).lean();return res.json({success:true,items:items.map(fmt)}); };
exports.getAdminOfferLetters = async (_req,res) => { const items=await OfferLetter.find().sort({createdAt:-1}).populate("userId","name email").populate("purchaseId","selectionStatus icatStatus interviewStatus").lean();return res.json({success:true,items}); };
exports.getAdminEligibleCandidates = async (_req,res) => { const items=await Purchase.find({paymentStatus:{$in:["paid","captured"]},$or:[{purchaseType:"internship"},{purchaseType:{$exists:false}}]}).select("userId internshipId durationLabel selectedDurationDays selectionStatus icatStatus interviewStatus createdAt").populate("userId","name email").populate("internshipId","title branch category").sort({createdAt:-1}).limit(100).lean(); const letters=await OfferLetter.find({purchaseId:{$in:items.map((item)=>item._id)}}).select("purchaseId offerLetterId status issueDate").lean();const byPurchase=new Map(letters.map((letter)=>[String(letter.purchaseId),letter])); return res.json({success:true,items:items.map((item)=>({...item,offerLetter:byPurchase.get(String(item._id))||null}))}); };
exports.updateCandidateSelection = async (req,res) => { if(!isValidObjectId(req.params.purchaseId))return res.status(400).json({success:false,message:"Invalid purchase ID."});const {selectionStatus,icatStatus,interviewStatus}=req.body||{};const allowed=["applied","icat_qualified","interview_scheduled","interview_completed","selected","rejected"];if(!allowed.includes(selectionStatus))return res.status(400).json({success:false,message:"Invalid selection status."});if(selectionStatus==="selected"&&(icatStatus!=="qualified"||interviewStatus!=="completed"))return res.status(400).json({success:false,message:"A candidate can be selected only after iCAT qualification and interview completion."});const purchase=await Purchase.findByIdAndUpdate(req.params.purchaseId,{$set:{selectionStatus,icatStatus,interviewStatus}},{new:true});return purchase?res.json({success:true,purchase}):res.status(404).json({success:false,message:"Purchase not found."}); };
exports.issueOfferLetter = async (req,res) => { try { if(!isValidObjectId(req.params.purchaseId))return res.status(400).json({success:false,message:"Invalid purchase ID."});const existing=await OfferLetter.findOne({purchaseId:req.params.purchaseId});if(existing)return res.status(409).json({success:false,message:"Offer letter already exists for this candidate.",offerLetter:fmt(existing)});const purchase=await Purchase.findById(req.params.purchaseId).populate("internshipId");if(!purchase||purchase.selectionStatus!=="selected"||purchase.icatStatus!=="qualified"||purchase.interviewStatus!=="completed")return res.status(400).json({success:false,message:"Only selected candidates who qualified iCAT and completed the online interview can receive an offer letter."});const user=await User.findById(purchase.userId).select("name email");if(!user)return res.status(400).json({success:false,message:"Candidate record not found."});const internship=purchase.internshipId;const startDate=purchase.createdAt||new Date();const endDate=new Date(new Date(startDate).getTime()+Math.max(1,Number(purchase.selectedDurationDays||0))*86400000);let letter;for(let n=0;n<3;n+=1){try{letter=await OfferLetter.create({offerLetterId:id(),purchaseId:purchase._id,userId:user._id,internshipId:internship._id,candidateName:user.name,candidateEmail:user.email,internshipTitle:internship.title,domain:internship.title,duration:purchase.durationLabel||`${purchase.selectedDurationDays||""} Days`,startDate,endDate,mode:"Online",internshipType:"Training Internship",selectionStatus:"selected",icatStatus:"qualified",interviewStatus:"completed"});break;}catch(e){if(e.code!==11000)throw e;}}if(!letter)throw new Error("Unable to allocate reference ID.");return res.status(201).json({success:true,message:"Offer letter issued successfully.",offerLetter:fmt(letter)});}catch(e){console.error("ISSUE OFFER LETTER ERROR:",e.message);return res.status(500).json({success:false,message:"Unable to issue offer letter."});} };
exports.revokeOfferLetter = async (req,res) => { const letter=await OfferLetter.findById(req.params.offerLetterId);if(!letter)return res.status(404).json({success:false,message:"Offer letter not found."});if(letter.status!=="revoked"){letter.status="revoked";letter.revokedAt=new Date();letter.revokedBy=req.user.id||req.user._id;await letter.save();}return res.json({success:true,message:"Offer letter revoked.",offerLetter:fmt(letter)}); };
