const PDFDocument = require("pdfkit");
const QRCode = require("qrcode");
const fs = require("fs");
const path = require("path");

const ADDRESS = "Plot No. D-24, Sector 3, Block D, Sector 12, Noida, Uttar Pradesh 201301";
const date = (value) => new Date(value || Date.now()).toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" });

module.exports = async function generateOfferLetterPdf({ res, offerLetter }) {
  const doc = new PDFDocument({ size: "A4", margin: 0, info: { Title: `InternovaTech Internship Offer Letter ${offerLetter.offerLetterId}`, Author: "InternovaTech" } });
  const W=595.28,H=841.89,L=48,R=547,CW=R-L,navy="#0B1F3A",royal="#173EA5",blue="#2563EB",ink="#172B4D",muted="#5B6B82",line="#D6E1F0",pale="#F6F9FE",gold="#B8872B";
  const logoPath=path.join(__dirname,"../uploads/branding/brand logo.png"),signaturePath=path.join(__dirname,"../assets/signature.png"), program=offerLetter.internshipTitle||offerLetter.domain||"Internship Program", verificationUrl=`https://www.internovatech.in/verify-offer-letter/${encodeURIComponent(offerLetter.offerLetterId)}`;
  const qr=await QRCode.toBuffer(verificationUrl,{width:140,margin:1,color:{dark:navy,light:"#FFFFFF"}});
  const field=(caption,content,x,y,width)=>{doc.font("Helvetica-Bold").fontSize(7.1).fillColor(muted).text(caption,x,y);doc.font("Helvetica-Bold").fontSize(9).fillColor(ink).text(String(content||"Not specified"),x,y+10,{width,ellipsis:true,lineBreak:false});};
  doc.pipe(res);
  doc.rect(0,0,W,H).fill("#FFFFFF");doc.lineWidth(1.4).strokeColor(navy).rect(18,18,W-36,H-36).stroke();doc.lineWidth(.45).strokeColor("#AFC3E5").rect(24,24,W-48,H-48).stroke();doc.fillColor(navy).rect(24,24,W-48,6).fill();doc.fillColor(gold).rect(24,30,W-48,2).fill();doc.save().opacity(.035).fillColor(royal).circle(542,86,60).fill().restore();
  if(fs.existsSync(logoPath)){try{doc.image(logoPath,L,48,{fit:[56,40]});}catch{}}
  doc.font("Helvetica-Bold").fontSize(20).fillColor(navy).text("InternovaTech",113,48).font("Helvetica").fontSize(7.7).fillColor(muted).text("ONLINE INTERNSHIP & CAREER DEVELOPMENT PLATFORM",114,72).font("Helvetica-Bold").fontSize(8).fillColor(royal).text("www.internovatech.in",114,86);
  doc.font("Helvetica-Bold").fontSize(8).fillColor(royal).text("INTERNSHIP OFFER LETTER",360,52,{width:187,align:"right"}).font("Helvetica").fontSize(7.6).fillColor(muted).text(`REF. ${offerLetter.offerLetterId}`,360,69,{width:187,align:"right"}).text(`ISSUED ${date(offerLetter.issueDate)}`,360,82,{width:187,align:"right"});doc.strokeColor(line).lineWidth(.8).moveTo(L,106).lineTo(R,106).stroke();
  doc.font("Helvetica-Bold").fontSize(18).fillColor(navy).text("INTERNSHIP OFFER LETTER",L,123,{width:CW,align:"center",characterSpacing:.7});doc.fillColor(gold).rect(255,151,85,2).fill();doc.font("Helvetica").fontSize(8.7).fillColor(muted).text("FORMAL OFFER OF INTERNSHIP",L,160,{width:CW,align:"center",characterSpacing:.6});
  doc.font("Helvetica").fontSize(9.2).fillColor(ink).text("To,",L,188).font("Helvetica-Bold").fontSize(10.5).text(offerLetter.candidateName,L,203).font("Helvetica").fontSize(8.7).fillColor(muted).text(offerLetter.candidateEmail,L,218);
  doc.font("Helvetica-Bold").fontSize(9).fillColor(ink).text(`Subject: Offer of Internship - ${program}`,L,248,{width:CW});doc.font("Helvetica").fontSize(9.1).text(`Dear ${offerLetter.candidateName},`,L,274).fontSize(8.8).text(`Following the successful completion of the InternovaTech Internship Common Aptitude Test (iCAT) and the subsequent Online Interview, we are pleased to offer you an internship opportunity with InternovaTech in ${program}.`,L,289,{width:CW,align:"justify",lineGap:1.5}).fontSize(8.65).text("This opportunity is designed to provide structured learning, practical exposure, and domain-relevant project activities that strengthen your professional skills.",L,329,{width:CW,align:"justify",lineGap:1.5});
  doc.roundedRect(L,363,CW,126,4).fillAndStroke(pale,line);doc.fillColor(navy).rect(L,363,CW,24).fill();doc.fillColor(gold).rect(L,385,CW,2).fill();doc.font("Helvetica-Bold").fontSize(9.5).fillColor("#FFFFFF").text("INTERNSHIP DETAILS",L+14,371,{characterSpacing:.4});field("CANDIDATE NAME",offerLetter.candidateName,L+14,401,218);field("INTERNSHIP DOMAIN",program,L+265,401,218);field("PROGRAM / INTERNSHIP TITLE",program,L+14,435,218);field("DURATION",offerLetter.duration,L+265,435,218);field("MODE",offerLetter.mode||"Online",L+14,465,218);field("INTERNSHIP TYPE",offerLetter.internshipType||"Training Internship",L+265,465,218);
  doc.font("Helvetica-Bold").fontSize(9.5).fillColor(navy).text("SELECTION BASIS",L,508);doc.strokeColor(line).lineWidth(.7).moveTo(L,524).lineTo(R,524).stroke();["Internship Common Aptitude Test (iCAT)","Online Interview","Final Selection"].forEach((item,index)=>{const x=L+index*164;doc.circle(x+5,543,5).fill(blue);doc.font("Helvetica-Bold").fontSize(9).fillColor(ink).text(item,x+17,537,{width:142});});
  doc.font("Helvetica-Bold").fontSize(9.5).fillColor(navy).text("RESPONSIBILITIES & EXPECTATIONS",L,568);doc.strokeColor(line).lineWidth(.7).moveTo(L,584).lineTo(R,584).stroke();["Complete assigned learning, practical activities and project work.","Follow internship guidelines, timelines and professional conduct standards.","Complete applicable assessments and maintain required progress."].forEach((item,index)=>{const y=598+index*15;doc.circle(L+4,y+4,2.2).fill(gold);doc.font("Helvetica").fontSize(8.25).fillColor(ink).text(item,L+14,y,{width:CW-14});});
  doc.font("Helvetica").fontSize(8.05).fillColor(ink).text("By accepting this offer, you acknowledge that you have read and understood the internship terms and agree to comply with the applicable InternovaTech internship guidelines.",L,649,{width:320,align:"justify",lineGap:1});doc.strokeColor(line).lineWidth(.7).moveTo(379,647).lineTo(525,647).stroke();if(fs.existsSync(signaturePath)){try{doc.image(signaturePath,389,654,{fit:[126,34]});}catch{}}doc.font("Helvetica-Bold").fontSize(9.4).fillColor(ink).text("Authorized Signatory",379,690).font("Helvetica").fontSize(8.1).fillColor(muted).text("Human Resources  |  InternovaTech\nhr@internovatech.in",379,704);
  doc.image(qr,L,692,{fit:[52,52]});doc.font("Helvetica-Bold").fontSize(8.2).fillColor(navy).text("DOCUMENT VERIFICATION",110,695).font("Helvetica").fontSize(7.2).fillColor(muted).text(`Reference ID: ${offerLetter.offerLetterId}\nVerify at: ${verificationUrl}`,110,709,{width:250,lineGap:1});doc.fillColor(navy).rect(24,770,W-48,39).fill();doc.fillColor(gold).rect(24,770,W-48,2).fill();doc.font("Helvetica").fontSize(7.1).fillColor("#FFFFFF").text(`InternovaTech  |  ${ADDRESS}`,L,782,{width:CW,align:"center"}).text("hr@internovatech.in  |  www.internovatech.in  |  System-generated document",L,794,{width:CW,align:"center"});doc.end();
};
